name: Validate CloudFormation

on:
  push:
    branches: [ main, infra/cloudformation ]
  pull_request:
    paths:
      - 'templates/**'
      - '.github/workflows/validate-cfn.yaml'
      - '.github/validation/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install yamllint cfn-lint

      - name: Run Validation Script
        run: |
          chmod +x .github/validation/validate-cfn.sh
          ./.github/validation/validate-cfn.sh
