# .github/workflows/validate-cfn.yaml
name: Validate CloudFormation

on:
  pull_request:
    paths:
      - 'templates/**'
      - '.github/workflows/validate-cfn.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install yamllint cfn-lint

      - name: Run Validation Script
        run: |
          chmod +x .github/validation/validate-cfn.sh
          ./.github/validation/validate-cfn.sh

      # - name: Install cfn-guard
      #   run: |
      #     curl -Lo cfn-guard.tar.gz https://github.com/aws-cloudformation/cloudformation-guard/releases/latest/download/cfn-guard-v3-ubuntu-latest.tar.gz
      #     tar xzf cfn-guard.tar.gz
      #     sudo mv cfn-guard /usr/local/bin/

      # - name: Check policy compliance
      #   run: |
      #     cfn-guard validate \
      #       --data templates/**/*.yaml \
      #       --rules policies/rules.guard

      # - name: AWS CloudFormation validate
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-east-1
      #   run: |
      #     for template in templates/*.yaml; do
      #       echo "Validating $template"
      #       aws cloudformation validate-template \
      #         --template-body "file://$template"
      #     done